### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by nighon** [serverless-components/tencent-fullstack#10]
我照着[腾讯云官网教程](https://cloud.tencent.com/document/product/1154/43009)一步一步，最后报错：

```
 Error: 401 - Your credentials do not have access to the Organization with the name of: fullstack.  Try logging into a different account.
    at Object.request (/home/vagrant/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/node_modules/@serverless/platform-client/src/utils.js:44:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

32s › tencent-fullstack › 401 - Your credentials do not have access to the Organization with the name of: fullstack.  Try logging into a different account.
```

**Comment by nighon** [comment]
这两个配置都确认有权限的：
TENCENT_SECRET_ID, TENCENT_SECRET_KEY

```
# .env
TENCENT_SECRET_ID=xxx  // 您账号的 SecretId
TENCENT_SECRET_KEY=xxx // 您账号的 SecretKey

# 地域可用区配置
REGION=ap-guangzhou //资源部署区，该项目中指云函数与静态页面部署区
ZONE=ap-guangzhou-2 //资源部署可用区 ，该项目中指 DB 部署所在的可用区
```

**Comment by AprilJC** [comment]
您好，该项目成功部署需要一下权限，请再次检查一下您的权限是否配置完全了呢
- QcloudPostgreSQLFullAccess
- QcloudSLSFullAccess
- QcloudAPIGWFullAccess
- QcloudSCFFullAccess
- QcloudCOSFullAccess
- QcloudMonitorFullAccess

**Comment by nighon** [comment]
你好，我用的是主账号的密钥。这些权限应该都默认开启的吧？

**Comment by AprilJC** [comment]
您好，因为 sls 使用 SLS_QcsRole 完成部署，这个角色具有的权限是需要自己添加的，登陆控制台-点击账户头像-访问管理-角色-SLS_QcsRole，查看一下该角色所具有的权限，如果缺少的话请手动添加

您可以参考一下我们的官方文档：
https://cloud.tencent.com/document/product/1154/43006
