### ISSUE TITLE
直接部署demo后，无法deploy

### ISSUE THREAD

**Issue by cc4dogman** [serverless-components/tencent-fullstack#6]
运行sls deploy --all之后
 Error: ENOENT: no such file or directory, stat 'F:\flyhh\tencent-fullstack\F:\flyhh\tencent-fullstack\frontend\dist'
    at Object.statSync (fs.js:855:3)
    at Object.statSync (C:\Users\RUAN\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\polyfills.js:308:16)
    at Object.getDirSize (C:\Users\RUAN\AppData\Roaming\npm\node_modules\serverless\node_modules\@serverless\platform-client-china\src\utils.js:158:21)
    at run (C:\Users\RUAN\AppData\Roaming\npm\node_modules\serverless\node_modules\@serverless\platform-client-china\src\instance.js:254:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)

32s » tencent-fullstack » ENOENT: no such file or directory, stat 'F:\flyhh\tencent-fullstack\F:\flyhh\tencent-fullstack\frontend\dist'

api db服务已经deploy成功了 看前端是目录处理有问题，修改frontend的serverless.yml文件，把dist对应改成./ 还是报一样的问题

**Comment by tinafangkunding** [comment]
在部署之前有执行 npm run bootstrap吗，前端应该需要构建完毕后再部署

**Comment by yugasun** [comment]
@cc4dogman 此项目是一个全面的全栈应用，部署前，请确认 api 和 frontend 中的模块依赖已经安装成功了。

**Comment by cc4dogman** [comment]
之前执行过 npm run bootstrap 只有frontend失败了

**Comment by tinafangkunding** [comment]
如果您这边 frontend 的依赖安装失败，那么在部署过程中也会有问题的，可以单独看一下在npm run 的时候，前端报错是怎样的呢
